version: '2'
services:
  proxy:
    build: .
    ports:
      - '8000:8000'
    
  product_review:
    image: mermanly/product_reviews
    depends_on:
      - 'database'
    ports:
      - '8002:8002'
  
  database:
    image: mongo:latest

  product_comparison:
    image: henrytheyang/product-comparison
    depends_on:
      - 'database'
    ports:
      - '8003:8003'
  
  database:
    image: mongo:latest

  related_products:
    image: ivyzheng/related-product:latest
    depends_on:
      - 'database'
    ports:
      - '8001:8001'
  
  database:
    image: mongo:latest

  product_overview:
    image: hanyuzhu/item_detail:latest
    depends_on:
      - 'database'
    ports:
      - '8004:8004'
  
  database:
    image: mongo:latest